// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: agentsandbox/v1/agent_sandbox.proto

package agentsandboxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkspaceKind int32

const (
	WorkspaceKind_WORKSPACE_KIND_UNSPECIFIED WorkspaceKind = 0
	WorkspaceKind_WORKSPACE_KIND_MANAGED     WorkspaceKind = 1
	WorkspaceKind_WORKSPACE_KIND_LOCAL_BOUND WorkspaceKind = 2
)

// Enum value maps for WorkspaceKind.
var (
	WorkspaceKind_name = map[int32]string{
		0: "WORKSPACE_KIND_UNSPECIFIED",
		1: "WORKSPACE_KIND_MANAGED",
		2: "WORKSPACE_KIND_LOCAL_BOUND",
	}
	WorkspaceKind_value = map[string]int32{
		"WORKSPACE_KIND_UNSPECIFIED": 0,
		"WORKSPACE_KIND_MANAGED":     1,
		"WORKSPACE_KIND_LOCAL_BOUND": 2,
	}
)

func (x WorkspaceKind) Enum() *WorkspaceKind {
	p := new(WorkspaceKind)
	*p = x
	return p
}

func (x WorkspaceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkspaceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_agentsandbox_v1_agent_sandbox_proto_enumTypes[0].Descriptor()
}

func (WorkspaceKind) Type() protoreflect.EnumType {
	return &file_agentsandbox_v1_agent_sandbox_proto_enumTypes[0]
}

func (x WorkspaceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkspaceKind.Descriptor instead.
func (WorkspaceKind) EnumDescriptor() ([]byte, []int) {
	return file_agentsandbox_v1_agent_sandbox_proto_rawDescGZIP(), []int{0}
}

type PolicyMode int32

const (
	PolicyMode_POLICY_MODE_UNSPECIFIED PolicyMode = 0
	PolicyMode_POLICY_MODE_READ_WRITE  PolicyMode = 1
	PolicyMode_POLICY_MODE_READ_ONLY   PolicyMode = 2
)

// Enum value maps for PolicyMode.
var (
	PolicyMode_name = map[int32]string{
		0: "POLICY_MODE_UNSPECIFIED",
		1: "POLICY_MODE_READ_WRITE",
		2: "POLICY_MODE_READ_ONLY",
	}
	PolicyMode_value = map[string]int32{
		"POLICY_MODE_UNSPECIFIED": 0,
		"POLICY_MODE_READ_WRITE":  1,
		"POLICY_MODE_READ_ONLY":   2,
	}
)

func (x PolicyMode) Enum() *PolicyMode {
	p := new(PolicyMode)
	*p = x
	return p
}

func (x PolicyMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicyMode) Descriptor() protoreflect.EnumDescriptor {
	return file_agentsandbox_v1_agent_sandbox_proto_enumTypes[1].Descriptor()
}

func (PolicyMode) Type() protoreflect.EnumType {
	return &file_agentsandbox_v1_agent_sandbox_proto_enumTypes[1]
}

func (x PolicyMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicyMode.Descriptor instead.
func (PolicyMode) EnumDescriptor() ([]byte, []int) {
	return file_agentsandbox_v1_agent_sandbox_proto_rawDescGZIP(), []int{1}
}

type CreateWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkspaceRequest) Reset() {
	*x = CreateWorkspaceRequest{}
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkspaceRequest) ProtoMessage() {}

func (x *CreateWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_agentsandbox_v1_agent_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWorkspaceRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type CreateWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkspaceResponse) Reset() {
	*x = CreateWorkspaceResponse{}
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkspaceResponse) ProtoMessage() {}

func (x *CreateWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_agentsandbox_v1_agent_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWorkspaceResponse) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

type Workspace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	WorktreePath  string                 `protobuf:"bytes,2,opt,name=worktree_path,json=worktreePath,proto3" json:"worktree_path,omitempty"`
	TreeHash      string                 `protobuf:"bytes,3,opt,name=tree_hash,json=treeHash,proto3" json:"tree_hash,omitempty"`
	Kind          WorkspaceKind          `protobuf:"varint,4,opt,name=kind,proto3,enum=agentsandbox.v1.WorkspaceKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_agentsandbox_v1_agent_sandbox_proto_rawDescGZIP(), []int{2}
}

func (x *Workspace) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Workspace) GetWorktreePath() string {
	if x != nil {
		return x.WorktreePath
	}
	return ""
}

func (x *Workspace) GetTreeHash() string {
	if x != nil {
		return x.TreeHash
	}
	return ""
}

func (x *Workspace) GetKind() WorkspaceKind {
	if x != nil {
		return x.Kind
	}
	return WorkspaceKind_WORKSPACE_KIND_UNSPECIFIED
}

type BindWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Binding       *WorkspaceBinding      `protobuf:"bytes,2,opt,name=binding,proto3" json:"binding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindWorkspaceRequest) Reset() {
	*x = BindWorkspaceRequest{}
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindWorkspaceRequest) ProtoMessage() {}

func (x *BindWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*BindWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_agentsandbox_v1_agent_sandbox_proto_rawDescGZIP(), []int{3}
}

func (x *BindWorkspaceRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *BindWorkspaceRequest) GetBinding() *WorkspaceBinding {
	if x != nil {
		return x.Binding
	}
	return nil
}

type WorkspaceBinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Source:
	//
	//	*WorkspaceBinding_Local
	Source        isWorkspaceBinding_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceBinding) Reset() {
	*x = WorkspaceBinding{}
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceBinding) ProtoMessage() {}

func (x *WorkspaceBinding) ProtoReflect() protoreflect.Message {
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceBinding.ProtoReflect.Descriptor instead.
func (*WorkspaceBinding) Descriptor() ([]byte, []int) {
	return file_agentsandbox_v1_agent_sandbox_proto_rawDescGZIP(), []int{4}
}

func (x *WorkspaceBinding) GetSource() isWorkspaceBinding_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *WorkspaceBinding) GetLocal() *LocalWorkspaceBinding {
	if x != nil {
		if x, ok := x.Source.(*WorkspaceBinding_Local); ok {
			return x.Local
		}
	}
	return nil
}

type isWorkspaceBinding_Source interface {
	isWorkspaceBinding_Source()
}

type WorkspaceBinding_Local struct {
	Local *LocalWorkspaceBinding `protobuf:"bytes,1,opt,name=local,proto3,oneof"`
}

func (*WorkspaceBinding_Local) isWorkspaceBinding_Source() {}

type LocalWorkspaceBinding struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Path            string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	CreateIfMissing bool                   `protobuf:"varint,2,opt,name=create_if_missing,json=createIfMissing,proto3" json:"create_if_missing,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LocalWorkspaceBinding) Reset() {
	*x = LocalWorkspaceBinding{}
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalWorkspaceBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalWorkspaceBinding) ProtoMessage() {}

func (x *LocalWorkspaceBinding) ProtoReflect() protoreflect.Message {
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalWorkspaceBinding.ProtoReflect.Descriptor instead.
func (*LocalWorkspaceBinding) Descriptor() ([]byte, []int) {
	return file_agentsandbox_v1_agent_sandbox_proto_rawDescGZIP(), []int{5}
}

func (x *LocalWorkspaceBinding) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LocalWorkspaceBinding) GetCreateIfMissing() bool {
	if x != nil {
		return x.CreateIfMissing
	}
	return false
}

type BindWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindWorkspaceResponse) Reset() {
	*x = BindWorkspaceResponse{}
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindWorkspaceResponse) ProtoMessage() {}

func (x *BindWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*BindWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_agentsandbox_v1_agent_sandbox_proto_rawDescGZIP(), []int{6}
}

func (x *BindWorkspaceResponse) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

type RunRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId     string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Command         string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Cwd             string                 `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Env             map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExposedBinaries []string               `protobuf:"bytes,5,rep,name=exposed_binaries,json=exposedBinaries,proto3" json:"exposed_binaries,omitempty"`
	TimeoutMs       uint64                 `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	PolicyMode      PolicyMode             `protobuf:"varint,7,opt,name=policy_mode,json=policyMode,proto3,enum=agentsandbox.v1.PolicyMode" json:"policy_mode,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_agentsandbox_v1_agent_sandbox_proto_rawDescGZIP(), []int{7}
}

func (x *RunRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *RunRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *RunRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *RunRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *RunRequest) GetExposedBinaries() []string {
	if x != nil {
		return x.ExposedBinaries
	}
	return nil
}

func (x *RunRequest) GetTimeoutMs() uint64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *RunRequest) GetPolicyMode() PolicyMode {
	if x != nil {
		return x.PolicyMode
	}
	return PolicyMode_POLICY_MODE_UNSPECIFIED
}

type RunResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExitCode       int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout         []byte                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr         []byte                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Runner         string                 `protobuf:"bytes,4,opt,name=runner,proto3" json:"runner,omitempty"`
	OpId           string                 `protobuf:"bytes,5,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	BeforeTreeHash string                 `protobuf:"bytes,6,opt,name=before_tree_hash,json=beforeTreeHash,proto3" json:"before_tree_hash,omitempty"`
	AfterTreeHash  string                 `protobuf:"bytes,7,opt,name=after_tree_hash,json=afterTreeHash,proto3" json:"after_tree_hash,omitempty"`
	Changed        bool                   `protobuf:"varint,8,opt,name=changed,proto3" json:"changed,omitempty"`
	Audit          *RunAudit              `protobuf:"bytes,9,opt,name=audit,proto3" json:"audit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_agentsandbox_v1_agent_sandbox_proto_rawDescGZIP(), []int{8}
}

func (x *RunResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *RunResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *RunResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *RunResponse) GetRunner() string {
	if x != nil {
		return x.Runner
	}
	return ""
}

func (x *RunResponse) GetOpId() string {
	if x != nil {
		return x.OpId
	}
	return ""
}

func (x *RunResponse) GetBeforeTreeHash() string {
	if x != nil {
		return x.BeforeTreeHash
	}
	return ""
}

func (x *RunResponse) GetAfterTreeHash() string {
	if x != nil {
		return x.AfterTreeHash
	}
	return ""
}

func (x *RunResponse) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *RunResponse) GetAudit() *RunAudit {
	if x != nil {
		return x.Audit
	}
	return nil
}

type RunAudit struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	WorkspaceId      string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Cwd              string                 `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	ExposedBinaries  []string               `protobuf:"bytes,4,rep,name=exposed_binaries,json=exposedBinaries,proto3" json:"exposed_binaries,omitempty"`
	TimeoutMs        uint64                 `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	DurationMs       uint64                 `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Runner           string                 `protobuf:"bytes,7,opt,name=runner,proto3" json:"runner,omitempty"`
	StartedAtUnixMs  int64                  `protobuf:"varint,8,opt,name=started_at_unix_ms,json=startedAtUnixMs,proto3" json:"started_at_unix_ms,omitempty"`
	FinishedAtUnixMs int64                  `protobuf:"varint,9,opt,name=finished_at_unix_ms,json=finishedAtUnixMs,proto3" json:"finished_at_unix_ms,omitempty"`
	StdoutBytes      uint64                 `protobuf:"varint,10,opt,name=stdout_bytes,json=stdoutBytes,proto3" json:"stdout_bytes,omitempty"`
	StderrBytes      uint64                 `protobuf:"varint,11,opt,name=stderr_bytes,json=stderrBytes,proto3" json:"stderr_bytes,omitempty"`
	PolicyMode       PolicyMode             `protobuf:"varint,12,opt,name=policy_mode,json=policyMode,proto3,enum=agentsandbox.v1.PolicyMode" json:"policy_mode,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RunAudit) Reset() {
	*x = RunAudit{}
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAudit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAudit) ProtoMessage() {}

func (x *RunAudit) ProtoReflect() protoreflect.Message {
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAudit.ProtoReflect.Descriptor instead.
func (*RunAudit) Descriptor() ([]byte, []int) {
	return file_agentsandbox_v1_agent_sandbox_proto_rawDescGZIP(), []int{9}
}

func (x *RunAudit) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RunAudit) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *RunAudit) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *RunAudit) GetExposedBinaries() []string {
	if x != nil {
		return x.ExposedBinaries
	}
	return nil
}

func (x *RunAudit) GetTimeoutMs() uint64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *RunAudit) GetDurationMs() uint64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *RunAudit) GetRunner() string {
	if x != nil {
		return x.Runner
	}
	return ""
}

func (x *RunAudit) GetStartedAtUnixMs() int64 {
	if x != nil {
		return x.StartedAtUnixMs
	}
	return 0
}

func (x *RunAudit) GetFinishedAtUnixMs() int64 {
	if x != nil {
		return x.FinishedAtUnixMs
	}
	return 0
}

func (x *RunAudit) GetStdoutBytes() uint64 {
	if x != nil {
		return x.StdoutBytes
	}
	return 0
}

func (x *RunAudit) GetStderrBytes() uint64 {
	if x != nil {
		return x.StderrBytes
	}
	return 0
}

func (x *RunAudit) GetPolicyMode() PolicyMode {
	if x != nil {
		return x.PolicyMode
	}
	return PolicyMode_POLICY_MODE_UNSPECIFIED
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_agentsandbox_v1_agent_sandbox_proto_rawDescGZIP(), []int{10}
}

func (x *StatusRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Runner        string                 `protobuf:"bytes,2,opt,name=runner,proto3" json:"runner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_agentsandbox_v1_agent_sandbox_proto_rawDescGZIP(), []int{11}
}

func (x *StatusResponse) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

func (x *StatusResponse) GetRunner() string {
	if x != nil {
		return x.Runner
	}
	return ""
}

type Operation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OpId           string                 `protobuf:"bytes,1,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	Command        string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	ExitCode       int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	BeforeTreeHash string                 `protobuf:"bytes,4,opt,name=before_tree_hash,json=beforeTreeHash,proto3" json:"before_tree_hash,omitempty"`
	AfterTreeHash  string                 `protobuf:"bytes,5,opt,name=after_tree_hash,json=afterTreeHash,proto3" json:"after_tree_hash,omitempty"`
	Changed        bool                   `protobuf:"varint,6,opt,name=changed,proto3" json:"changed,omitempty"`
	Audit          *RunAudit              `protobuf:"bytes,7,opt,name=audit,proto3" json:"audit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_agentsandbox_v1_agent_sandbox_proto_rawDescGZIP(), []int{12}
}

func (x *Operation) GetOpId() string {
	if x != nil {
		return x.OpId
	}
	return ""
}

func (x *Operation) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Operation) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *Operation) GetBeforeTreeHash() string {
	if x != nil {
		return x.BeforeTreeHash
	}
	return ""
}

func (x *Operation) GetAfterTreeHash() string {
	if x != nil {
		return x.AfterTreeHash
	}
	return ""
}

func (x *Operation) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *Operation) GetAudit() *RunAudit {
	if x != nil {
		return x.Audit
	}
	return nil
}

type ListOperationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationsRequest) Reset() {
	*x = ListOperationsRequest{}
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationsRequest) ProtoMessage() {}

func (x *ListOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationsRequest.ProtoReflect.Descriptor instead.
func (*ListOperationsRequest) Descriptor() ([]byte, []int) {
	return file_agentsandbox_v1_agent_sandbox_proto_rawDescGZIP(), []int{13}
}

func (x *ListOperationsRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ListOperationsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOperationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListOperationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*Operation           `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationsResponse) Reset() {
	*x = ListOperationsResponse{}
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationsResponse) ProtoMessage() {}

func (x *ListOperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationsResponse.ProtoReflect.Descriptor instead.
func (*ListOperationsResponse) Descriptor() ([]byte, []int) {
	return file_agentsandbox_v1_agent_sandbox_proto_rawDescGZIP(), []int{14}
}

func (x *ListOperationsResponse) GetOperations() []*Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *ListOperationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	OpId          string                 `protobuf:"bytes,2,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_agentsandbox_v1_agent_sandbox_proto_rawDescGZIP(), []int{15}
}

func (x *GetOperationRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *GetOperationRequest) GetOpId() string {
	if x != nil {
		return x.OpId
	}
	return ""
}

type GetOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *Operation             `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationResponse) Reset() {
	*x = GetOperationResponse{}
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationResponse) ProtoMessage() {}

func (x *GetOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentsandbox_v1_agent_sandbox_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationResponse.ProtoReflect.Descriptor instead.
func (*GetOperationResponse) Descriptor() ([]byte, []int) {
	return file_agentsandbox_v1_agent_sandbox_proto_rawDescGZIP(), []int{16}
}

func (x *GetOperationResponse) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

var File_agentsandbox_v1_agent_sandbox_proto protoreflect.FileDescriptor

const file_agentsandbox_v1_agent_sandbox_proto_rawDesc = "" +
	"\n" +
	"#agentsandbox/v1/agent_sandbox.proto\x12\x0fagentsandbox.v1\";\n" +
	"\x16CreateWorkspaceRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"S\n" +
	"\x17CreateWorkspaceResponse\x128\n" +
	"\tworkspace\x18\x01 \x01(\v2\x1a.agentsandbox.v1.WorkspaceR\tworkspace\"\xa4\x01\n" +
	"\tWorkspace\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12#\n" +
	"\rworktree_path\x18\x02 \x01(\tR\fworktreePath\x12\x1b\n" +
	"\ttree_hash\x18\x03 \x01(\tR\btreeHash\x122\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x1e.agentsandbox.v1.WorkspaceKindR\x04kind\"v\n" +
	"\x14BindWorkspaceRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12;\n" +
	"\abinding\x18\x02 \x01(\v2!.agentsandbox.v1.WorkspaceBindingR\abinding\"\\\n" +
	"\x10WorkspaceBinding\x12>\n" +
	"\x05local\x18\x01 \x01(\v2&.agentsandbox.v1.LocalWorkspaceBindingH\x00R\x05localB\b\n" +
	"\x06source\"W\n" +
	"\x15LocalWorkspaceBinding\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12*\n" +
	"\x11create_if_missing\x18\x02 \x01(\bR\x0fcreateIfMissing\"Q\n" +
	"\x15BindWorkspaceResponse\x128\n" +
	"\tworkspace\x18\x01 \x01(\v2\x1a.agentsandbox.v1.WorkspaceR\tworkspace\"\xd3\x02\n" +
	"\n" +
	"RunRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\x126\n" +
	"\x03env\x18\x04 \x03(\v2$.agentsandbox.v1.RunRequest.EnvEntryR\x03env\x12)\n" +
	"\x10exposed_binaries\x18\x05 \x03(\tR\x0fexposedBinaries\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\x04R\ttimeoutMs\x12<\n" +
	"\vpolicy_mode\x18\a \x01(\x0e2\x1b.agentsandbox.v1.PolicyModeR\n" +
	"policyMode\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa4\x02\n" +
	"\vRunResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\fR\x06stderr\x12\x16\n" +
	"\x06runner\x18\x04 \x01(\tR\x06runner\x12\x13\n" +
	"\x05op_id\x18\x05 \x01(\tR\x04opId\x12(\n" +
	"\x10before_tree_hash\x18\x06 \x01(\tR\x0ebeforeTreeHash\x12&\n" +
	"\x0fafter_tree_hash\x18\a \x01(\tR\rafterTreeHash\x12\x18\n" +
	"\achanged\x18\b \x01(\bR\achanged\x12/\n" +
	"\x05audit\x18\t \x01(\v2\x19.agentsandbox.v1.RunAuditR\x05audit\"\xc1\x03\n" +
	"\bRunAudit\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\x12)\n" +
	"\x10exposed_binaries\x18\x04 \x03(\tR\x0fexposedBinaries\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\x04R\ttimeoutMs\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x04R\n" +
	"durationMs\x12\x16\n" +
	"\x06runner\x18\a \x01(\tR\x06runner\x12+\n" +
	"\x12started_at_unix_ms\x18\b \x01(\x03R\x0fstartedAtUnixMs\x12-\n" +
	"\x13finished_at_unix_ms\x18\t \x01(\x03R\x10finishedAtUnixMs\x12!\n" +
	"\fstdout_bytes\x18\n" +
	" \x01(\x04R\vstdoutBytes\x12!\n" +
	"\fstderr_bytes\x18\v \x01(\x04R\vstderrBytes\x12<\n" +
	"\vpolicy_mode\x18\f \x01(\x0e2\x1b.agentsandbox.v1.PolicyModeR\n" +
	"policyMode\"2\n" +
	"\rStatusRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"b\n" +
	"\x0eStatusResponse\x128\n" +
	"\tworkspace\x18\x01 \x01(\v2\x1a.agentsandbox.v1.WorkspaceR\tworkspace\x12\x16\n" +
	"\x06runner\x18\x02 \x01(\tR\x06runner\"\xf4\x01\n" +
	"\tOperation\x12\x13\n" +
	"\x05op_id\x18\x01 \x01(\tR\x04opId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12(\n" +
	"\x10before_tree_hash\x18\x04 \x01(\tR\x0ebeforeTreeHash\x12&\n" +
	"\x0fafter_tree_hash\x18\x05 \x01(\tR\rafterTreeHash\x12\x18\n" +
	"\achanged\x18\x06 \x01(\bR\achanged\x12/\n" +
	"\x05audit\x18\a \x01(\v2\x19.agentsandbox.v1.RunAuditR\x05audit\"v\n" +
	"\x15ListOperationsRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"|\n" +
	"\x16ListOperationsResponse\x12:\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\x1a.agentsandbox.v1.OperationR\n" +
	"operations\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"M\n" +
	"\x13GetOperationRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x13\n" +
	"\x05op_id\x18\x02 \x01(\tR\x04opId\"P\n" +
	"\x14GetOperationResponse\x128\n" +
	"\toperation\x18\x01 \x01(\v2\x1a.agentsandbox.v1.OperationR\toperation*k\n" +
	"\rWorkspaceKind\x12\x1e\n" +
	"\x1aWORKSPACE_KIND_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16WORKSPACE_KIND_MANAGED\x10\x01\x12\x1e\n" +
	"\x1aWORKSPACE_KIND_LOCAL_BOUND\x10\x02*`\n" +
	"\n" +
	"PolicyMode\x12\x1b\n" +
	"\x17POLICY_MODE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16POLICY_MODE_READ_WRITE\x10\x01\x12\x19\n" +
	"\x15POLICY_MODE_READ_ONLY\x10\x022\xa8\x04\n" +
	"\x13AgentSandboxService\x12d\n" +
	"\x0fCreateWorkspace\x12'.agentsandbox.v1.CreateWorkspaceRequest\x1a(.agentsandbox.v1.CreateWorkspaceResponse\x12^\n" +
	"\rBindWorkspace\x12%.agentsandbox.v1.BindWorkspaceRequest\x1a&.agentsandbox.v1.BindWorkspaceResponse\x12@\n" +
	"\x03Run\x12\x1b.agentsandbox.v1.RunRequest\x1a\x1c.agentsandbox.v1.RunResponse\x12I\n" +
	"\x06Status\x12\x1e.agentsandbox.v1.StatusRequest\x1a\x1f.agentsandbox.v1.StatusResponse\x12a\n" +
	"\x0eListOperations\x12&.agentsandbox.v1.ListOperationsRequest\x1a'.agentsandbox.v1.ListOperationsResponse\x12[\n" +
	"\fGetOperation\x12$.agentsandbox.v1.GetOperationRequest\x1a%.agentsandbox.v1.GetOperationResponseBTZRgithub.com/agent-sandbox/agent-sandbox/sdk/go/proto/agentsandbox/v1;agentsandboxv1b\x06proto3"

var (
	file_agentsandbox_v1_agent_sandbox_proto_rawDescOnce sync.Once
	file_agentsandbox_v1_agent_sandbox_proto_rawDescData []byte
)

func file_agentsandbox_v1_agent_sandbox_proto_rawDescGZIP() []byte {
	file_agentsandbox_v1_agent_sandbox_proto_rawDescOnce.Do(func() {
		file_agentsandbox_v1_agent_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agentsandbox_v1_agent_sandbox_proto_rawDesc), len(file_agentsandbox_v1_agent_sandbox_proto_rawDesc)))
	})
	return file_agentsandbox_v1_agent_sandbox_proto_rawDescData
}

var file_agentsandbox_v1_agent_sandbox_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agentsandbox_v1_agent_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_agentsandbox_v1_agent_sandbox_proto_goTypes = []any{
	(WorkspaceKind)(0),              // 0: agentsandbox.v1.WorkspaceKind
	(PolicyMode)(0),                 // 1: agentsandbox.v1.PolicyMode
	(*CreateWorkspaceRequest)(nil),  // 2: agentsandbox.v1.CreateWorkspaceRequest
	(*CreateWorkspaceResponse)(nil), // 3: agentsandbox.v1.CreateWorkspaceResponse
	(*Workspace)(nil),               // 4: agentsandbox.v1.Workspace
	(*BindWorkspaceRequest)(nil),    // 5: agentsandbox.v1.BindWorkspaceRequest
	(*WorkspaceBinding)(nil),        // 6: agentsandbox.v1.WorkspaceBinding
	(*LocalWorkspaceBinding)(nil),   // 7: agentsandbox.v1.LocalWorkspaceBinding
	(*BindWorkspaceResponse)(nil),   // 8: agentsandbox.v1.BindWorkspaceResponse
	(*RunRequest)(nil),              // 9: agentsandbox.v1.RunRequest
	(*RunResponse)(nil),             // 10: agentsandbox.v1.RunResponse
	(*RunAudit)(nil),                // 11: agentsandbox.v1.RunAudit
	(*StatusRequest)(nil),           // 12: agentsandbox.v1.StatusRequest
	(*StatusResponse)(nil),          // 13: agentsandbox.v1.StatusResponse
	(*Operation)(nil),               // 14: agentsandbox.v1.Operation
	(*ListOperationsRequest)(nil),   // 15: agentsandbox.v1.ListOperationsRequest
	(*ListOperationsResponse)(nil),  // 16: agentsandbox.v1.ListOperationsResponse
	(*GetOperationRequest)(nil),     // 17: agentsandbox.v1.GetOperationRequest
	(*GetOperationResponse)(nil),    // 18: agentsandbox.v1.GetOperationResponse
	nil,                             // 19: agentsandbox.v1.RunRequest.EnvEntry
}
var file_agentsandbox_v1_agent_sandbox_proto_depIdxs = []int32{
	4,  // 0: agentsandbox.v1.CreateWorkspaceResponse.workspace:type_name -> agentsandbox.v1.Workspace
	0,  // 1: agentsandbox.v1.Workspace.kind:type_name -> agentsandbox.v1.WorkspaceKind
	6,  // 2: agentsandbox.v1.BindWorkspaceRequest.binding:type_name -> agentsandbox.v1.WorkspaceBinding
	7,  // 3: agentsandbox.v1.WorkspaceBinding.local:type_name -> agentsandbox.v1.LocalWorkspaceBinding
	4,  // 4: agentsandbox.v1.BindWorkspaceResponse.workspace:type_name -> agentsandbox.v1.Workspace
	19, // 5: agentsandbox.v1.RunRequest.env:type_name -> agentsandbox.v1.RunRequest.EnvEntry
	1,  // 6: agentsandbox.v1.RunRequest.policy_mode:type_name -> agentsandbox.v1.PolicyMode
	11, // 7: agentsandbox.v1.RunResponse.audit:type_name -> agentsandbox.v1.RunAudit
	1,  // 8: agentsandbox.v1.RunAudit.policy_mode:type_name -> agentsandbox.v1.PolicyMode
	4,  // 9: agentsandbox.v1.StatusResponse.workspace:type_name -> agentsandbox.v1.Workspace
	11, // 10: agentsandbox.v1.Operation.audit:type_name -> agentsandbox.v1.RunAudit
	14, // 11: agentsandbox.v1.ListOperationsResponse.operations:type_name -> agentsandbox.v1.Operation
	14, // 12: agentsandbox.v1.GetOperationResponse.operation:type_name -> agentsandbox.v1.Operation
	2,  // 13: agentsandbox.v1.AgentSandboxService.CreateWorkspace:input_type -> agentsandbox.v1.CreateWorkspaceRequest
	5,  // 14: agentsandbox.v1.AgentSandboxService.BindWorkspace:input_type -> agentsandbox.v1.BindWorkspaceRequest
	9,  // 15: agentsandbox.v1.AgentSandboxService.Run:input_type -> agentsandbox.v1.RunRequest
	12, // 16: agentsandbox.v1.AgentSandboxService.Status:input_type -> agentsandbox.v1.StatusRequest
	15, // 17: agentsandbox.v1.AgentSandboxService.ListOperations:input_type -> agentsandbox.v1.ListOperationsRequest
	17, // 18: agentsandbox.v1.AgentSandboxService.GetOperation:input_type -> agentsandbox.v1.GetOperationRequest
	3,  // 19: agentsandbox.v1.AgentSandboxService.CreateWorkspace:output_type -> agentsandbox.v1.CreateWorkspaceResponse
	8,  // 20: agentsandbox.v1.AgentSandboxService.BindWorkspace:output_type -> agentsandbox.v1.BindWorkspaceResponse
	10, // 21: agentsandbox.v1.AgentSandboxService.Run:output_type -> agentsandbox.v1.RunResponse
	13, // 22: agentsandbox.v1.AgentSandboxService.Status:output_type -> agentsandbox.v1.StatusResponse
	16, // 23: agentsandbox.v1.AgentSandboxService.ListOperations:output_type -> agentsandbox.v1.ListOperationsResponse
	18, // 24: agentsandbox.v1.AgentSandboxService.GetOperation:output_type -> agentsandbox.v1.GetOperationResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_agentsandbox_v1_agent_sandbox_proto_init() }
func file_agentsandbox_v1_agent_sandbox_proto_init() {
	if File_agentsandbox_v1_agent_sandbox_proto != nil {
		return
	}
	file_agentsandbox_v1_agent_sandbox_proto_msgTypes[4].OneofWrappers = []any{
		(*WorkspaceBinding_Local)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agentsandbox_v1_agent_sandbox_proto_rawDesc), len(file_agentsandbox_v1_agent_sandbox_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agentsandbox_v1_agent_sandbox_proto_goTypes,
		DependencyIndexes: file_agentsandbox_v1_agent_sandbox_proto_depIdxs,
		EnumInfos:         file_agentsandbox_v1_agent_sandbox_proto_enumTypes,
		MessageInfos:      file_agentsandbox_v1_agent_sandbox_proto_msgTypes,
	}.Build()
	File_agentsandbox_v1_agent_sandbox_proto = out.File
	file_agentsandbox_v1_agent_sandbox_proto_goTypes = nil
	file_agentsandbox_v1_agent_sandbox_proto_depIdxs = nil
}
